# -*- coding: utf-8 -*-
"""2.1 - Repositorio de software compartido que contendrá los componentes desarrollados en esta fase..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DRC006bG80K4CVw44Th9dLUh4wW4PJJM
"""

#En esta clase, la clase Mascota tiene métodos para alimentar y jugar con la mascota, y un método especial para determinar su estado emocional.
#También utilize propiedades para acceder al nombre, edad y nivel de felicidad de la mascota, y le agregue emojis para darle un toque chido.


import random

class Mascota:
    def __init__(self, nombre, edad):
        self._nombre = nombre
        self._edad = edad
        self._nivel_felicidad = 50

    @property
    def nombre(self):
        return f"🌟{self._nombre}🌟"  # Agrega emojis al nombre de la mascota

    @property
    def edad(self):
        return f"{self._edad} años"  # Devuelve la edad de la mascota

    @property
    def nivel_felicidad(self):
        return self._nivel_felicidad  # Devuelve el nivel de felicidad de la mascota

    def alimentar(self):
        print(f"{self.nombre} dice: ¡Ñam ñam! ¡Gracias por la comida!")  # Imprime un mensaje al alimentar
        self._nivel_felicidad += 10

    def jugar(self):
        print(f"{self.nombre} dice: ¡Estoy tan feliz jugando contigo!")  # Imprime un mensaje al jugar
        self._nivel_felicidad += random.randint(5, 15)  # Aumenta la felicidad de forma aleatoria

    def estado_emocional(self):
        if self._nivel_felicidad >= 70:
            return "¡Estoy muy feliz!"  # Retorna mensaje si la mascota está muy feliz
        elif 50 <= self._nivel_felicidad < 70:
            return "Estoy contento."  # Retorna mensaje si la mascota está contenta
        else:
            return "Estoy un poco triste. ¿Podemos jugar más?"  # Retorna mensaje si la mascota está triste

# Crear una instancia de la clase Mascota
mi_mascota = Mascota(nombre="Firulais", edad=2)

# Interactuar con la mascota
mi_mascota.alimentar()
mi_mascota.jugar()

# Obtener información y estado emocional de la mascota
nombre_mascota = mi_mascota.nombre
edad_mascota = mi_mascota.edad
estado_emocional_mascota = mi_mascota.estado_emocional()

# Mostrar resultados
nombre_mascota, edad_mascota, estado_emocional_mascota