# -*- coding: utf-8 -*-
"""3.1 - Repositorio de software compartido que contendrá los componentes desarrollados en esta fase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gj8aFyvhqDWftf4_AmBoyFUerJ3cQSUh
"""

#En este código, Hosmar, el valiente Héroe del Escudo, es guardado en el “Cristal de Memoria” (un archivo pickle).
#Cuando un gran mal se cierne sobre el reino, Hosmar es invocado desde las profundidades del Cristal de Memoria.
#Recuerda, siempre maneja los Cristales de Memoria con cuidado, solo debes abrir los que tú mismo has creado o los que provienen de una fuente confiable.





# Aqui importe el módulo pickle, que permite serializar y deserializar objetos.
import pickle

# Cree nuestro valiente héroe, Hosmar, como un diccionario de Python. (mi nombre xd)
hosmar = {"nombre": "Hosmar", "titulo": "Héroe del Escudo", "habilidad": "Defensa Absoluta"}

# cree un archivo llamado 'cristal_de_memoria.pickle' en modo de escritura binaria ('wb').
with open('cristal_de_memoria.pickle', 'wb') as cristal:
    # Use la función dump de pickle para serializar el objeto hosmar y guardarlo en el archivo.
    pickle.dump(hosmar, cristal)

# Imprimo un mensaje para indicar que Hosmar ha sido guardado en el Cristal de Memoria.
print("Hosmar, el valiente Héroe del Escudo, ha sido guardado en el Cristal de Memoria.")

# Abro el archivo 'cristal_de_memoria.pickle' en modo de lectura binaria ('rb').
with open('cristal_de_memoria.pickle', 'rb') as cristal:
    # aqui utilizo la función load de pickle para deserializar el objeto desde el archivo.
    heroe_invocado = pickle.load(cristal)

# aqui se imprime el objeto deserializado, que debería ser igual al objeto original hosmar.
print("Desde las profundidades del Cristal de Memoria, hemos invocado a nuestro héroe:", heroe_invocado)